"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SEARCH_ENGINE_URLS = exports.SENT_EVENT_VALIDITY_PERIOD_MS = exports.SENT_EVENT_ID_KEY = exports.TRAFFIC_TAG_KEY = exports.TRAFFIC_TITLE_KEY = exports.TRAFFIC_CATEGORY_KEY = exports.TRAFFIC_SOURCE_KEY = exports.REFERRER_ID_KEY = exports.PROJECT_ID_KEY = exports.TRACKING_ID_KEY = exports.SESSION_ID_KEY = void 0;
exports.SESSION_ID_KEY = "fuul.session_id";
exports.TRACKING_ID_KEY = "fuul.tracking_id";
exports.PROJECT_ID_KEY = "fuul.project_id";
exports.REFERRER_ID_KEY = "fuul.referrer_id";
exports.TRAFFIC_SOURCE_KEY = "fuul.traffic_source";
exports.TRAFFIC_CATEGORY_KEY = "fuul.traffic_category";
exports.TRAFFIC_TITLE_KEY = "fuul.traffic_title";
exports.TRAFFIC_TAG_KEY = "fuul.traffic_tag";
exports.SENT_EVENT_ID_KEY = "fuul.sent";
exports.SENT_EVENT_VALIDITY_PERIOD_MS = 60000;
exports.SEARCH_ENGINE_URLS = ["google.com", "bing.com", "yahoo.com"];
