"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getReferrerId = exports.getCampaignId = exports.getTrackingId = exports.getSessionId = void 0;
const constants_js_1 = require("../constants.js");
const getSessionId = () => localStorage.getItem(constants_js_1.SESSION_ID_KEY);
exports.getSessionId = getSessionId;
const getTrackingId = () => localStorage.getItem(constants_js_1.TRACKING_ID_KEY);
exports.getTrackingId = getTrackingId;
const getCampaignId = () => localStorage.getItem(constants_js_1.CAMPAIGN_ID_KEY);
exports.getCampaignId = getCampaignId;
const getReferrerId = () => localStorage.getItem(constants_js_1.REFERRER_ID_KEY);
exports.getReferrerId = getReferrerId;
