"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getTrafficTag = exports.getTrafficTitle = exports.getTrafficCategory = exports.getTrafficSource = exports.getReferrerId = exports.getProjectId = exports.getTrackingId = exports.getSessionId = void 0;
const constants_js_1 = require("../constants.js");
const getSessionId = () => localStorage.getItem(constants_js_1.SESSION_ID_KEY);
exports.getSessionId = getSessionId;
const getTrackingId = () => localStorage.getItem(constants_js_1.TRACKING_ID_KEY);
exports.getTrackingId = getTrackingId;
const getProjectId = () => localStorage.getItem(constants_js_1.PROJECT_ID_KEY);
exports.getProjectId = getProjectId;
const getReferrerId = () => localStorage.getItem(constants_js_1.REFERRER_ID_KEY);
exports.getReferrerId = getReferrerId;
const getTrafficSource = () => localStorage.getItem(constants_js_1.TRAFFIC_SOURCE_KEY);
exports.getTrafficSource = getTrafficSource;
const getTrafficCategory = () => localStorage.getItem(constants_js_1.TRAFFIC_CATEGORY_KEY);
exports.getTrafficCategory = getTrafficCategory;
const getTrafficTitle = () => localStorage.getItem(constants_js_1.TRAFFIC_TITLE_KEY);
exports.getTrafficTitle = getTrafficTitle;
const getTrafficTag = () => localStorage.getItem(constants_js_1.TRAFFIC_TAG_KEY);
exports.getTrafficTag = getTrafficTag;
